var lessons = [
    {
      id: 1,
      Subject: "Maths",
      Location: "London",
      Price: 150,
      Space: 5,
      image: "images/Maths.jpg",
      icon: "fa-solid fa-calculator",
    },
    {
      id: 2,
      Subject: "Biology",
      Location: "Hendon",
      Price: 200,
      Space: 5,
      image: "images/Biology.jpg",
      icon: "fa-solid fa-flask",
    },
    {
      id: 3,
      Subject: "Computer Science",
      Location: "London",
      Price: 250,
      Space: 5,
      image: "images/ComputerScience.jpg",
      icon: "fa-solid fa-laptop",
    },
    {
      id: 4,
      Subject: "AI",
      Location: "Birmingham",
      Price: 220,
      Space: 5,
      image: "images/Artificial Intelligence.jpg",
      icon: "fa-solid fa-laptop",
    },
    {
      id: 5,
      Subject: "Synoptics",
      Location: "Bristol",
      Price: 80,
      Space: 5,
      image: "images/Synoptics.jpg",
      icon: "fa fa-plus",
    },
    {
      id: 6,
      Subject: "Music",
      Location: "Birmingham",
      Price: 90,
      Space: 5,
      image: "images/Music.jpg",
      icon: "fa-solid fa-music",
    },
    {
      id: 7,
      Subject: "Networking",
      Location: "York",
      Price: 110,
      Space: 5,
      image: "images/Networking.jpg",
      icon: "fa fa-user-circle",
    },
    {
      id: 8,
      Subject: "Web Application",
      Location: "Essex",
      Price: 230,
      Space: 5,
      image: "images/WEB.jpg",
      icon: "fa-solid fa-calculator",
    },
    {
      id: 9,
      Subject: "Geography",
      Location: "Oxford",
      Price: 75,
      Space: 5,
      image: "images/geography.jpg",
      icon: "fa-solid fa-globe",
    },
    {
      id: 10,
      Subject: "Secure System",
      Location: "London",
      Price: 145,
      Space: 5,
      image: "images/DesignSecureSystem.jpg",
      icon: "fa fa-lock",
    },
	{
      id: 11,
      Subject: "Dancing",
      Location: "London",
      Price: 245,
      Space: 5,
      image: "images/Dancing.jpg",
      icon: "fa fa-lock",
    },
	{
      id: 12,
      Subject: "Singing",
      Location: "Bristol",
      Price: 123,
      Space: 5,
      image: "images/Singing.jpg",
      icon: "fa fa-lock",
    },
  ];
  
  